# Generated by Django 2.0.3 on 2018-03-17 01:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Att_date', models.DateTimeField(verbose_name='Attendance Date')),
            ],
            options={
                'verbose_name': 'Attendance Info',
                'verbose_name_plural': 'Attendance Info',
            },
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.DateTimeField(verbose_name='Class time')),
                ('class_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wendsday', 'Wendsday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, verbose_name='Class day')),
                ('class_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'intermediate'), ('Advanced', 'Advanced')], max_length=50, verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Class Info',
                'verbose_name_plural': 'Class Info',
            },
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('std_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="child's ID")),
            ],
            options={
                'verbose_name': 'Parent Info',
                'verbose_name_plural': 'Parent Info',
            },
        ),
        migrations.CreateModel(
            name='Rank_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RD_color', models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Half Green', 'Half Green'), ('Green', 'Green'), ('Half Blue', 'Half Blue'), ('Blue', 'Blue'), ('Half Red', 'Half Red'), ('Red', 'Red'), ('Half Black', 'Half Black'), ('Black', 'Black')], default='White', max_length=50, verbose_name='Rank Colors')),
                ('RD_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Rank Record Date')),
                ('std_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Student's ID")),
            ],
            options={
                'verbose_name': 'Rank Record Info',
                'verbose_name_plural': 'Rank Record Info',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_type', models.CharField(choices=[('membership', 'membership'), ('tests', 'tests'), ('purchasing products', 'purchasing products')], max_length=50, verbose_name='Transaction Type')),
                ('tr_date', models.DateTimeField(verbose_name='Transaction Date')),
                ('tr_amount', models.IntegerField(default=0, verbose_name='Transaction Amount')),
                ('std_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Student's ID")),
            ],
            options={
                'verbose_name': 'Transaction Info',
                'verbose_name_plural': 'Transaction Info',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.ClassInfo', verbose_name="class' ID"),
        ),
        migrations.AddField(
            model_name='attendance',
            name='std_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Student's ID"),
        ),
    ]
