# Generated by Django 2.0.3 on 2018-03-20 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_userprofile_stu_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.ClassInfo', verbose_name="Class' ID"),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='std_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Student's Name"),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='std_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Student's Name"),
        ),
        migrations.AlterField(
            model_name='rank_record',
            name='std_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Student's Name"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='std_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Student's Name"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stu_class',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.ClassInfo', verbose_name="Student's Class"),
        ),
    ]
