# Generated by Django 2.0.3 on 2018-03-21 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20180320_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stu_class',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='students.ClassInfo', verbose_name="Student's Class"),
        ),
    ]
