# Generated by Django 2.0.3 on 2018-03-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20180320_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='class_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Class time'),
        ),
    ]
