# Generated by Django 2.0.3 on 2018-03-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20180321_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='class_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wendsday', 'Wendsday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True, verbose_name='Class day'),
        ),
    ]
